version: "3"
services:
  jmusicbot:
    build: .
    command: ./jmusicbot.sh
    container_name: jmusicbot
    ports:
      - 443:443
    secrets:
      - source: token
        target: token
      - source: owner
        target: owner
secrets:
  token:
    environment: "TOKEN"
  owner:
    environment: "OWNER"
