services:
  jmusicbot:
    build:
      context: .
      network: host
      args:
        DOWNLOAD_URL: ${DOWNLOAD_URL}
    command: ./jmusicbot.sh
    container_name: jmusicbot
    ports:
      - 443:443
    secrets:
      - source: token
        target: token
      - source: owner
        target: owner
secrets:
  token:
    environment: "TOKEN"
  owner:
    environment: "OWNER"
